name: passkey
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  hive: ^2.2.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  delightful_toast: ^1.1.0
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  qr_flutter: ^4.1.0
  table_calendar: ^3.1.2
  equatable: ^2.0.5
  get_it: ^8.0.2
  http: ^1.2.2
  flutter_stripe: ^11.3.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/.env

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-BoldItalic.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-LightItalic.ttf
        - asset: fonts/OpenSans-Medium.ttf
        - asset: fonts/OpenSans-MediumItalic.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
